config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/' => 'homepage#index'

  root to: "homepage#index"

  get 'surveys' => 'surveys#index'

  resource :surveys, only: [:index, :new, :create]

  resource :microaggressions, only: [:new, :create, :index]

end

app/models/microaggression.rb
class Microaggression < ActiveRecord::Base

	AGG = %w(boss coworker subordinate patron)

	belongs_to :user

end

app/models/survey.rb
class Survey < ActiveRecord::Base

	GENDERS = ["Other","Non-gender Conforming","Gender-fluid","Agender","Trans-Femme","Trans-Masc","Female","Male","Unsure"]
	RESPONSES = %w(Yes No Maybe)
	RACES = ['Other',"Black", "Asian","Indian","Mixed-Race","Latino/Latina", "Native-American","White"]
	INDUSTRIES = %w(Real-estate Healthcare/Medicine Law Technology Marketing/Advertising Finance Non-profit Retail Food-industry Government Transportation Education Agriculture Mining Construction Arts/Entertainment Social-Services Other)

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

	validates :zipcode, :gender, :race, :age, :faced_microaggressions, :seen_microaggressions, :industry, presence: true

	validates :email, format: {with: VALID_EMAIL_REGEX, message: "%{value} does not match the valid e-mail format."}, allow_blank:true, allow_nil:true

end

app/models/user.rb
class User < ActiveRecord::Base

	GENDERS = ["Other","Non-gender Conforming","Gender-fluid","Agender","Trans-Femme","Trans-Masc","Female","Male","Unsure"]
	RESPONSES = %w(Yes No Maybe)
	RACES = ['Other',"Black", "Asian","Indian","Mixed-Race","Latino/Latina", "Native-American","White"]
	INDUSTRIES = %w(Real-estate Healthcare/Medicine Law Technology Marketing/Advertising Finance Non-profit Retail Food-industry Government Transportation Education Agriculture Mining Construction Arts/Entertainment Social-Services Other)

	has_many :microaggressions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
	def index
	end
end

app/controllers/microaggressions_controller.rb
require 'pry'

class MicroaggressionsController < ApplicationController

	def new
		@micro = Microaggression.new
	end

	def create
		@micro = Microaggression.new(micro_params)
		binding.pry
		@micro.user = current_user
		if @micro.valid?
			@micro.save
			redirect_to "/"
		else
			render 'new'
		end
	end

	def index
		@micros = Microaggression.all
	end

	private
		def micro_params
			params.require(:microaggression).permit(:user,:location,:description,:aggressor,:severity)
		end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	def index
	end

	def new
		@survey = Survey.new
	end

	def create
		@survey = Survey.new(survey_params)
		if @survey.valid?
			@survey.save
			redirect_to surveys_path
		else
			render 'new'
		end
	end

	private
		def survey_params
			params.require(:survey).permit(:zipcode,:gender,:race,:industry,:age,:email,:faced_microaggressions,:seen_microaggressions)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/microaggression_helper.rb
module MicroaggressionHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/views/homepage/index.html.erb
<div class="indexBackground"></div>

<% if current_user %>
	<h1 class="currentUser"> Welcome <%= current_user.email%></h1>
	<h3>
		<%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
	</h3>
<% end %>

<div class="main">
	<h1>Welcome to <span class="heroText">The Micro-aggression Monitor</span></h1>
	<span class="introText">This is a website aimed at monitoring micro (and macro) aggressions within under-represented communities in the workplace.</span>
	<% if !current_user %>
		<div class="mainButton">
			<span class="contribute"> <%= link_to "Contribute", new_surveys_path%> </span> 
			<span class="login "> <%= link_to "Login", new_user_session_path %></span>
		</div>
	<% else %>
		<div class="mainButton">
			<span> <%= link_to "Record a Microaggression!", new_microaggressions_path %></span>
		</div>
	<% end %>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheEffWasThat</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"\>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
	<%= yield %>
	<div id="modal-holder"></div>

</body>
</html>

app/views/layouts/modal.html.erb
<div class="modal" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="mainModalLabel">
          <%= yield :title if content_for? :title %>&nbsp;
        </h4>
      </div>

      <%= yield %>
    </div>
  </div>
</div>

app/views/microaggressions/new.html.erb
<h1 class="microaggressionFormHeader"> Thanks! </h1>

<% if @micro.errors.any? %>
	<h1 class="error"> Hm...something wetn wrong</h1>
	<% @micro.errors.each do |err| %>
		<ul>
			<li><%= err %> </li>
		</ul>
	<% end %>
<% end %> 

<%= form_for @micro do |f| %>

	<%= f.label :location, "Location" %>
	<%= f.text_field :location %>

	<%= f.label :description, "Description" %>
	<%= f.text_field :description%>

	<%= f.label :aggressor, "Aggressor" %>
	<%= select("microaggression","aggressor", Microaggression::AGG, {include_blank:true}) %>

	<%= f.label :severity, "Severity" %>
	<%= select_tag "severity",options_for_select(1..5) %>

	<%= f.submit "Submit", class:"submitMicro" %>
<% end %>

app/views/surveys/index.html.erb
<%= link_to 'Home', root_path %>

<h1>Thanks!</h1>

<h2> For more information about Microaggressions, check out this resources! </h2>
<ul>
	<li><a href="https://en.wikipedia.org/wiki/Microaggression_theory"> Wikipedia!</a></li>
	<li><a href="https://www.buzzfeed.com/hnigatu/racial-microagressions-you-hear-on-a-daily-basis?utm_term=.sjo5NVY7K#.kfNbdzWJ2">Buzzfeed Wrote Something!</a></li>
	<li><a href="http://www.microaggressions.com/">A (Sort of) Good Blog on Microaggressions</a></li>
</ul>

app/views/surveys/new.html.erb
<h1 class="surveyHeader">Thanks for Filling Out This Form!</h1>

<% if @survey.errors.any? %>
	<h1 class="error">Hm..something went wrong</h1>
<% end %>

<div class="survey">
	<%= form_for @survey do |f| %>
		
		<%= f.label :zipcode, "Zipcode" %>
		<%= f.text_field :zipcode %>

		<%= f.label  :gender, "Gender" %>	
		<%= select("survey","gender", Survey::GENDERS, {include_blank:true}) %>

		<%= f.label :race, "Race" %>	
		<%= select("survey", "race", Survey::RACES, {include_blank:true}) %>

		<%= f.label :industry, "Industry" %>
		<%= select("survey", "industry", Survey::INDUSTRIES, {include_blank:true})%>

		<%= f.label :age, "Age"%>	
		<%= f.text_field :age %>

		<%= f.label :email, "Email" %>	
		<%= f.text_field :email %>

		<%= f.label :faced_microaggressions, "Faced Microaggressions?", class: "simpleResponse" %>	
		<%= select("survey","faced_microaggressions", Survey::RESPONSES, {include_blank:true}) %>

		<%= f.label :seen_microaggressions, "Seen Microaggressions?", class: "simpleResponse" %>
		<%= select("survey","seen_microaggressions", Survey::RESPONSES, {include_blank:true}) %>

		<%= f.submit "Submit", class: "submitSurvey" %>
	<% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>